# Generated by Django 2.1 on 2018-09-16 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterid', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='章节主键')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='消息内容')),
                ('comefrom', models.CharField(default='', max_length=500, verbose_name='来路')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户咨询',
                'verbose_name_plural': '用户咨询',
            },
        ),
        migrations.CreateModel(
            name='UserZan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelDetail', to_field='url_md5', verbose_name='小说')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
            },
        ),
    ]
