# Generated by Django 2.1 on 2018-10-08 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userzan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='novelfavorite',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelDetail', to_field='url_md5', verbose_name='小说'),
        ),
        migrations.AddField(
            model_name='novelfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='novelfavorite',
            unique_together={('user', 'novel')},
        ),
        migrations.AlterIndexTogether(
            name='novelfavorite',
            index_together={('user', 'novel', 'chapterid')},
        ),
    ]
