# Generated by Django 2.1 on 2018-09-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180916_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelfavorite',
            old_name='update_time',
            new_name='create_time',
        ),
    ]
