# Generated by Django 2.1 on 2018-09-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180923_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userask',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAsk',
        ),
    ]
