# Generated by Django 2.1 on 2018-10-01 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180928_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userzan',
            name='create_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='添加时间'),
        ),
    ]
