# Generated by Django 2.1 on 2018-10-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20181001_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userzan',
            unique_together=set(),
        ),
    ]
