# Generated by Django 2.1 on 2018-10-02 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20181001_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelfavorite',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
