# Generated by Django 2.1 on 2018-10-02 21:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_remove_noveldetail_first_chapter_addr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0008_novelfavorite_update_time'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='novelfavorite',
            index_together={('user', 'novel', 'chapterid')},
        ),
    ]
