# Generated by Django 2.1 on 2018-10-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchtime', models.IntegerField(default=0, verbose_name='更新时间戳')),
                ('keywords', models.CharField(max_length=60, verbose_name='搜索词')),
                ('searchtype', models.CharField(choices=[('name', '书名'), ('author', '作者')], default='name', max_length=8)),
                ('results', models.SmallIntegerField(default=0, verbose_name='结果数量')),
                ('ids', models.TextField(verbose_name='小说id')),
            ],
        ),
    ]
