# Generated by Django 2.1 on 2018-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcache',
            name='results',
            field=models.SmallIntegerField(default=0, verbose_name='结果数量'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='searchtime',
            field=models.IntegerField(default=1537943953, verbose_name='更新时间戳'),
        ),
    ]
