# Generated by Django 2.1 on 2018-09-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180926_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcache',
            name='keywords',
            field=models.CharField(max_length=60, verbose_name='搜索词'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='searchtime',
            field=models.IntegerField(default=0, verbose_name='更新时间戳'),
        ),
    ]
