# Generated by Django 2.1 on 2018-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='olduserid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='老用户ID'),
        ),
    ]
