# Generated by Django 2.1 on 2018-09-23 21:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userqiandao'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_bid', models.IntegerField(default=0, verbose_name='小说ID')),
                ('fav_cid', models.IntegerField(default=0, verbose_name='小说章节ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='upload/image/default.png', max_length=300, null=True, upload_to=users.models.user_directory_path, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userqiandao',
            name='qiandao_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='签到时间'),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'fav_bid')},
        ),
    ]
