# Generated by Django 2.1 on 2018-09-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180923_2117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
