# Generated by Django 2.1 on 2018-09-16 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('chapter_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('chapter_name', models.CharField(max_length=300, verbose_name='章节名')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('chapter_type', models.BooleanField(default=False, verbose_name='是否为卷标')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter_order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('chapter_old_id', models.IntegerField(default=0, verbose_name='对于老站编号')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
            },
        ),
        migrations.CreateModel(
            name='NovelClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20, unique=True, verbose_name='分类')),
                ('sortid', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='分类ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
            },
        ),
        migrations.CreateModel(
            name='NovelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('chapter', models.ManyToManyField(to='novels.NovelChapter')),
            ],
        ),
        migrations.CreateModel(
            name='NovelContentComefrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comefrom', models.CharField(max_length=20, unique=True, verbose_name='来源网站')),
                ('comefrom_id', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='来源ID')),
                ('ishide', models.BooleanField(default=False, verbose_name='是否隐藏')),
            ],
            options={
                'verbose_name': '小说内容来源',
                'verbose_name_plural': '小说内容来源',
            },
        ),
        migrations.CreateModel(
            name='NovelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='来源地址')),
                ('url_md5', models.CharField(max_length=50, unique=True, verbose_name='查询主键')),
                ('novel_name', models.CharField(max_length=300, verbose_name='小说名')),
                ('novel_author', models.CharField(max_length=300, verbose_name='作者')),
                ('novel_comefrom', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='来源网站')),
                ('first_chapter_addr', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='第一个章节地址')),
                ('novel_info', models.TextField(blank=True, default='', null=True, verbose_name='小说简介')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('novel_old_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='对于老站编号')),
                ('novel_fav_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏人数')),
                ('novel_zan_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='推荐人数')),
                ('novel_click_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='点击数')),
                ('novel_status', models.BooleanField(default=False, verbose_name='是否完本')),
                ('ishide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('image', models.ImageField(blank=True, default='courses/default.png', max_length=300, null=True, upload_to='courses/%Y/%m/%d', verbose_name='封面图')),
                ('novelclassify', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelClassify', to_field='sortid', verbose_name='小说类型')),
            ],
            options={
                'verbose_name': '小说详情',
                'verbose_name_plural': '小说详情',
            },
        ),
        migrations.AddField(
            model_name='novelcontent',
            name='comefrom',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源'),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='noveldetail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='novels.NovelDetail', to_field='url_md5', verbose_name='小说详情'),
        ),
        migrations.AlterUniqueTogether(
            name='noveldetail',
            unique_together={('novel_name', 'novel_author', 'novel_comefrom')},
        ),
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('novel_old_id',)},
        ),
    ]
