# Generated by Django 2.1 on 2018-09-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelcontent',
            name='ishide',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否隐藏'),
        ),
        migrations.AlterField(
            model_name='novelcontentcomefrom',
            name='comefrom_id',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='权重'),
        ),
    ]
