# Generated by Django 2.1 on 2018-10-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chaptercontent',
            unique_together={('novelchapter', 'novelcontent')},
        ),
    ]
