# Generated by Django 2.1 on 2018-09-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20180917_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noveldetail',
            name='first_chapter_addr',
        ),
    ]
