# Generated by Django 2.1 on 2018-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20181008_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='noveldetail',
            name='have_chapter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否有章节'),
        ),
    ]
