# Generated by Django 2.1 on 2018-10-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_noveldetail_have_chapter'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('have_chapter',), ('novel_old_id',)},
        ),
    ]
