# Generated by Django 2.1 on 2018-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20181011_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelcontent',
            options={'verbose_name': '小说内容', 'verbose_name_plural': '小说内容'},
        ),
        migrations.AddField(
            model_name='novelcontent',
            name='jiami',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是加密'),
        ),
        migrations.AddField(
            model_name='noveldetail',
            name='caiji_url_md5',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='判断采集url'),
        ),
        migrations.AlterIndexTogether(
            name='novelcontent',
            index_together={('jiami',), ('ishide',)},
        ),
    ]
