# Generated by Django 2.1 on 2018-10-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20181014_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='noveldetail',
            name='iswenziname',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否文字标题'),
        ),
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('iswenziname',), ('have_chapter',), ('novel_old_id',)},
        ),
    ]
