# Generated by Django 2.1 on 2018-10-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_auto_20181014_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelcontent',
            name='jiami',
        ),
        migrations.AlterIndexTogether(
            name='novelcontent',
            index_together={('ishide',)},
        ),
    ]
