# Generated by Django 2.1 on 2018-10-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_auto_20181015_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptercontent',
            name='ishide',
        ),
        migrations.AddField(
            model_name='novelcontent',
            name='ishide',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏'),
        ),
        migrations.RemoveField(
            model_name='novelcontent',
            name='feiqi',
        ),
        migrations.AlterIndexTogether(
            name='novelcontent',
            index_together={('ishide',)},
        ),
        migrations.RemoveField(
            model_name='noveldetail',
            name='caiji_url_md5',
        ),
        migrations.RemoveField(
            model_name='noveldetail',
            name='iswenziname',
        ),
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('have_chapter',), ('novel_old_id',)},
        ),
    ]
