# Generated by Django 2.1 on 2018-10-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_auto_20181015_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='noveldetail',
            name='caiji_url_md5',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='判断采集url'),
        ),
        migrations.AddField(
            model_name='noveldetail',
            name='iswenziname',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否文字标题'),
        ),
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('iswenziname',), ('novel_old_id',), ('have_chapter',)},
        ),
    ]
