# Generated by Django 2.1 on 2018-10-15 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_auto_20181015_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNewContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentEight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentNine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentSix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNewContentTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('novelchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelChapter', to_field='chapter_url_md5', verbose_name='章节内')),
            ],
        ),
        migrations.CreateModel(
            name='NovelNewContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContent', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentEight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentEight', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentFive', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentFour', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentNine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentNine', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentOne', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentSeven', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentSix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentSix', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentThree', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.CreateModel(
            name='NovelNewContentTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('num_words', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计字数')),
                ('content_url', models.CharField(default='', max_length=500, verbose_name='来源地址')),
                ('content_url_md5', models.CharField(default='', max_length=50, unique=True, verbose_name='查询主键')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('ishide', models.BooleanField(blank=True, default=False, null=True, verbose_name='是隐藏')),
                ('chapter', models.ManyToManyField(through='novels.ChapterNewContentTwo', to='novels.NovelChapter')),
                ('comefrom', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.NovelContentComefrom', to_field='comefrom_id', verbose_name='小说来源')),
            ],
            options={
                'verbose_name': '小说内容',
                'verbose_name_plural': '小说内容',
            },
        ),
        migrations.AddField(
            model_name='chapternewcontenttwo',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentTwo', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentthree',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentThree', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentsix',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentSix', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentseven',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentSeven', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentone',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentOne', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentnine',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentNine', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentfour',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentFour', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontentfive',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentFive', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontenteight',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContentEight', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AddField(
            model_name='chapternewcontent',
            name='novelcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelNewContent', to_field='content_url_md5', verbose_name='章节内容'),
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontenttwo',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentthree',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentsix',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentseven',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentone',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentnine',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentfour',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontentfive',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontenteight',
            index_together={('ishide',)},
        ),
        migrations.AlterIndexTogether(
            name='novelnewcontent',
            index_together={('ishide',)},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontenttwo',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentthree',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentsix',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentseven',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentone',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentnine',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentfour',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontentfive',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontenteight',
            unique_together={('novelchapter', 'novelcontent')},
        ),
        migrations.AlterUniqueTogether(
            name='chapternewcontent',
            unique_together={('novelchapter', 'novelcontent')},
        ),
    ]
