# Generated by Django 2.1 on 2018-10-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_auto_20181015_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noveldetail',
            name='caiji_url_md5',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='判断采集url'),
        ),
    ]
