# Generated by Django 2.1 on 2018-10-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0015_auto_20181016_0009'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('iswenziname',), ('stop_update',), ('update_time',), ('create_time',), ('have_chapter',), ('novel_old_id',), ('ishide',)},
        ),
    ]
