# Generated by Django 2.1 on 2018-10-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0016_auto_20181016_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='chapter_old_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='对于老站编号'),
        ),
        migrations.AlterField(
            model_name='novelchapter',
            name='chapter_type',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否为卷标'),
        ),
    ]
