# Generated by Django 2.1 on 2018-10-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0017_auto_20181016_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='chapter_type',
            field=models.BooleanField(default=False, verbose_name='是否为卷标'),
        ),
        migrations.AlterUniqueTogether(
            name='novelchapter',
            unique_together={('noveldetail', 'chapter_order')},
        ),
    ]
