# Generated by Django 2.1 on 2018-10-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0018_auto_20181016_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='noveldetail',
            name='caiji_status',
            field=models.CharField(choices=[('ys', '原始'), ('th', '替换'), ('tj', '添加')], default='ys', max_length=2, verbose_name='采集状态'),
        ),
    ]
