# Generated by Django 2.1 on 2018-10-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0019_noveldetail_caiji_status'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='noveldetail',
            index_together={('update_time',), ('novel_old_id',), ('ishide',), ('create_time',), ('have_chapter',), ('caiji_status',), ('stop_update',), ('iswenziname',)},
        ),
    ]
