# Generated by Django 2.1 on 2018-10-19 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0020_auto_20181018_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20, unique=True, verbose_name='tag')),
                ('tagid', models.PositiveSmallIntegerField(default=0, verbose_name='tagid')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '小说Tag',
                'verbose_name_plural': '小说Tag',
            },
        ),
        migrations.AddField(
            model_name='noveldetail',
            name='tag',
            field=models.ManyToManyField(to='novels.NovelTag'),
        ),
    ]
