# Generated by Django 2.1 on 2018-10-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0022_noveldetail_chapter_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptercontent',
            name='isdel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterIndexTogether(
            name='chaptercontent',
            index_together={('isdel',)},
        ),
    ]
