# Generated by Django 2.1 on 2018-11-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0025_auto_20181028_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='noveldetail',
            name='must_update',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必须更新'),
        ),
    ]
